/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package citymart;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class LoginAuthentication extends javax.swing.JFrame {
  
    Connection conn;
    PreparedStatement ps;
    
    public LoginAuthentication() {
        initComponents();
        
          
        this.setLocationRelativeTo(null); // center form in the screen
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        
        
         try {
            String url = "jdbc:mysql://localhost/citymart";
            String user = "root";
            String pass = "";
            
            conn = DriverManager.getConnection(url, user, pass);
           
    }catch(Exception ex){
             System.err.println("Error : "+ex.getMessage());
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        unM = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pwM = new javax.swing.JPasswordField();
        rtpwM = new javax.swing.JPasswordField();
        chkboxM1 = new javax.swing.JCheckBox();
        chkboxM2 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();
        userID2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        unSK = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pwSK = new javax.swing.JPasswordField();
        rtpwSK = new javax.swing.JPasswordField();
        chkboxSk1 = new javax.swing.JCheckBox();
        chkboxSK2 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        userID1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        unA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pwA = new javax.swing.JPasswordField();
        rtpwA = new javax.swing.JPasswordField();
        chkboxA1 = new javax.swing.JCheckBox();
        chkboxA2 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        userID3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Manager Login"));

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("username");

        jLabel3.setText("password");

        jLabel4.setText("retype password");

        chkboxM1.setText("Show Password");
        chkboxM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxM1ActionPerformed(evt);
            }
        });

        chkboxM2.setText("Show Password");
        chkboxM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxM2ActionPerformed(evt);
            }
        });

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setText("User ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)))
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rtpwM, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addComponent(unM)
                        .addComponent(userID2))
                    .addComponent(pwM, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkboxM1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton1)))
                    .addComponent(chkboxM2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(userID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pwM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(chkboxM1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtpwM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(chkboxM2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Store keeper Login"));

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("username");

        jLabel6.setText("password");

        jLabel7.setText("retype password");

        chkboxSk1.setText("Show Password");
        chkboxSk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxSk1ActionPerformed(evt);
            }
        });

        chkboxSK2.setText("Show Password");
        chkboxSK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxSK2ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel11.setText("User ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)))
                .addGap(104, 104, 104)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rtpwSK, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(unSK)
                    .addComponent(pwSK)
                    .addComponent(userID1))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(chkboxSk1)
                                .addGap(26, 26, 26)
                                .addComponent(jButton2))
                            .addComponent(chkboxSK2))
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(52, 52, 52))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(userID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unSK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pwSK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(chkboxSk1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtpwSK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(chkboxSK2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Accountant Login"));

        jLabel8.setText("username");

        jLabel9.setText("password");

        jLabel10.setText("retype password");

        chkboxA1.setText("Show Password");
        chkboxA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxA1ActionPerformed(evt);
            }
        });

        chkboxA2.setText("Show Password");
        chkboxA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxA2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ok");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel13.setText("User ID");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(35, 35, 35)))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rtpwA, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(unA)
                            .addComponent(pwA)
                            .addComponent(userID3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkboxA1)
                                    .addComponent(chkboxA2))
                                .addGap(37, 37, 37)
                                .addComponent(jButton3))
                            .addComponent(jButton6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pwA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkboxA1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rtpwA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkboxA2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(31, 31, 31))
        );

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Position", "Manager", "Store Keeper", "Accountant" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.setDoubleBuffered(true);
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel1.setText("Create User login Authentication");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
      
       
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
          String combo = jComboBox1.getSelectedItem().toString();
        
        switch(combo){
            case "Manager":
                jPanel2.setVisible(true);
                jPanel3.setVisible(false);
                jPanel4.setVisible(false);
                break;
                
            case "Store Keeper":
                jPanel3.setVisible(true);
                jPanel2.setVisible(false);
                jPanel4.setVisible(false);
                break;
                
            case "Accountant":
                jPanel4.setVisible(true);
                jPanel2.setVisible(false);
                jPanel3.setVisible(false);
                break;
                
            case "Select Position":
                jPanel2.setVisible(false);
                jPanel3.setVisible(false);
                jPanel4.setVisible(false);
                break;
        }
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // StoreKeeperOK
    
         
       if(userID1.getText().trim().isEmpty() || unSK.getText().trim().isEmpty() || pwSK.getText().trim().isEmpty() || rtpwSK.getText().trim().isEmpty())
       {
           
           JOptionPane.showMessageDialog(this,"Please Fill All Fields!!! ");
       }else{
           

            try {
                String uID = userID1.getText();
                String un = unSK.getText();
                String pw = pwSK.getText();
                String rtpw = rtpwSK.getText();
              
                if (pw.equals(rtpw)) {
                    
                    
                    String sql = "INSERT INTO store_keeper VALUES (?,?,?,?)";
                    ps = conn.prepareStatement(sql);

                    ps.setString(1, uID);
                    ps.setString(2, un);
                    ps.setString(3, pw);
                    ps.setString(4, rtpw);
                  
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, " User Successful Registered!!!!!!!!!!!!!");
                    
                    this.dispose();
                    ManagerManager mnger = new ManagerManager();
                    mnger.setVisible(true);
                                 
                } else {
                    JOptionPane.showMessageDialog(this, "Your password and Retype password not matched! Please check and try again!", 
                            "ERROR!", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception ex) {
                System.err.println("Error :" + ex.getMessage());
            }
       }
        
    }//GEN-LAST:event_jButton2ActionPerformed

     public void DeleteStoreK()
    {
           try{
          
        String sql= "DELETE FROM store_keeper WHERE User_ID";
        ps = conn.prepareStatement(sql);
       
        ps.executeUpdate(); 
            //JOptionPane.showMessageDialog(null,"Record Deleted successfully!!! ");
           // DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
           // model.setRowCount(0);
            //show_users();
            
           
        }catch(Exception ex){
            System.err.println("Error :"+ ex.getMessage());
        }
    }
    
    private void chkboxSk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxSk1ActionPerformed
        // showpassword
        if(chkboxSk1.isSelected()){
            pwSK.setEchoChar((char) 0);
        }else{
            pwSK.setEchoChar('*');
        }
    }//GEN-LAST:event_chkboxSk1ActionPerformed

    private void chkboxSK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxSK2ActionPerformed
        // showpassword
         if(chkboxSK2.isSelected()){
            rtpwSK.setEchoChar((char) 0);
        }else{
            rtpwSK.setEchoChar('*');
        }
    }//GEN-LAST:event_chkboxSK2ActionPerformed

    private void chkboxM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxM1ActionPerformed
        // showpassword
         if(chkboxM1.isSelected()){
            pwM.setEchoChar((char) 0);
        }else{
            pwM.setEchoChar('*');
        }
    }//GEN-LAST:event_chkboxM1ActionPerformed

    private void chkboxM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxM2ActionPerformed
        // showpassword
         if(chkboxM2.isSelected()){
            rtpwM.setEchoChar((char) 0);
        }else{
            rtpwM.setEchoChar('*');
        }
    }//GEN-LAST:event_chkboxM2ActionPerformed

    private void chkboxA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxA1ActionPerformed
        // showpassword
         if(chkboxA1.isSelected()){
            pwA.setEchoChar((char) 0);
        }else{
            pwA.setEchoChar('*');
        }
    }//GEN-LAST:event_chkboxA1ActionPerformed

    private void chkboxA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxA2ActionPerformed
        // showpassword
         if(chkboxA2.isSelected()){
            rtpwA.setEchoChar((char) 0);
        }else{
            rtpwA.setEchoChar('*');
        }
    }//GEN-LAST:event_chkboxA2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          // ManagerOK
    
         
       if(userID2.getText().trim().isEmpty() || unM.getText().trim().isEmpty() || pwM.getText().trim().isEmpty() || rtpwM.getText().trim().isEmpty())
       {
           
           JOptionPane.showMessageDialog(this,"Please Fill All Fields!!! ");
       }else{
           

            try {
                String uID1 = userID2.getText();
                String un1 = unM.getText();
                String pw1 = pwM.getText();
                String rtpw1 = rtpwM.getText();
              
                if (pw1.equals(rtpw1)) {
                    
                    
                    String sql = "INSERT INTO manager_login VALUES (?,?,?,?)";
                    ps = conn.prepareStatement(sql);

                    ps.setString(1, uID1);
                    ps.setString(2, un1);
                    ps.setString(3, pw1);
                    ps.setString(4, rtpw1);
                  
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, " User Successful Registered!!!!!!!!!!!!!");
                    
                    this.dispose();
                    ManagerManager mnger = new ManagerManager();
                    mnger.setVisible(true);
                                 
                } else {
                    JOptionPane.showMessageDialog(this, "Your password and Retype password not matched! Please check and try again!", 
                            "ERROR!", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception ex) {
                System.err.println("Error :" + ex.getMessage());
            }
       }
     
    }//GEN-LAST:event_jButton1ActionPerformed

     public void DeleteManager()
    {
           try{
           
        
        String sql= "DELETE FROM manager_login WHERE User_ID";
        ps = conn.prepareStatement(sql);
        
        
        
        ps.executeUpdate(); 
            JOptionPane.showMessageDialog(null,"User Record Deleted successfully!!! ");
           // DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
           // model.setRowCount(0);
            //show_users();
            
           
        }catch(Exception ex){
            System.err.println("Error :"+ ex.getMessage());
        }
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          // AccountantOK
    
         
       if(userID3.getText().trim().isEmpty() || unA.getText().trim().isEmpty() || pwA.getText().trim().isEmpty() || rtpwA.getText().trim().isEmpty())
       {
           
           JOptionPane.showMessageDialog(this,"Please Fill All Fields!!! ");
       }else{
           

            try {
                String uID2 = userID3.getText(); 
                String un2 = unA.getText();
                String pw2 = pwA.getText();
                String rtpw2 = rtpwA.getText();
              
                if (pw2.equals(rtpw2)) {
                    
                    
                    String sql = "INSERT INTO accountant_login VALUES (?,?,?,?)";
                    ps = conn.prepareStatement(sql);

                    ps.setString(1, uID2);
                    ps.setString(2, un2);
                    ps.setString(3, pw2);
                    ps.setString(4, rtpw2);
                  
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, " User Login authentication created succesfully!!!");
                    
                    this.dispose();
                    ManagerManager mnger = new ManagerManager();
                    mnger.setVisible(true);
                 
                                 
                } else {
                    JOptionPane.showMessageDialog(this, "Your password and Retype password not matched! Please check and try again!", 
                            "ERROR!", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception ex) {
                System.err.println("Error :" + ex.getMessage());
            }
       }
     
    }//GEN-LAST:event_jButton3ActionPerformed

       public void DeleteAccountant()
    {
           try{
         
        
        String sql= "DELETE FROM accountant_login WHERE User_ID";
        ps = conn.prepareStatement(sql);
        
        
        ps.executeUpdate(); 
            JOptionPane.showMessageDialog(null,"Record Deleted successfully!!! ");
           // DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
           // model.setRowCount(0);
            //show_users();
            
           
        }catch(Exception ex){
            System.err.println("Error :"+ ex.getMessage());
        }
    }
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         // Delete Button***********************************************************
        try{
            String id = unSK.getText();
        
        String sql= "DELETE FROM store_keeper WHERE Username=?";
        ps = conn.prepareStatement(sql);
        
        
        ps.setString(1,id);
        
        if (ps.executeUpdate()>0) {
            JOptionPane.showMessageDialog(this,"Deleted");
        }
        }catch(Exception ex){
            System.err.println("Error : "+ex.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            // Delete Button***************************************************
        try{
            String id1 = unM.getText();
        
        String sql= "DELETE FROM manager_login WHERE Username=?";
        ps = conn.prepareStatement(sql);
        
        
        ps.setString(1,id1);
        
        if (ps.executeUpdate()>0) {
            JOptionPane.showMessageDialog(this,"Deleted");
        }
        }catch(Exception ex){
            System.err.println("Error : "+ex.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
            // Delete Button****************************************************
        try{
            String id2 = unA.getText();
        
        String sql= "DELETE FROM accountant_login WHERE Username=?";
        ps = conn.prepareStatement(sql);
        
        
        ps.setString(1,id2);
        
        if (ps.executeUpdate()>0) {
            JOptionPane.showMessageDialog(this,"Deleted");
        }
        }catch(Exception ex){
            System.err.println("Error : "+ex.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAuthentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAuthentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAuthentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAuthentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAuthentication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkboxA1;
    private javax.swing.JCheckBox chkboxA2;
    private javax.swing.JCheckBox chkboxM1;
    private javax.swing.JCheckBox chkboxM2;
    private javax.swing.JCheckBox chkboxSK2;
    private javax.swing.JCheckBox chkboxSk1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField pwA;
    private javax.swing.JPasswordField pwM;
    private javax.swing.JPasswordField pwSK;
    private javax.swing.JPasswordField rtpwA;
    private javax.swing.JPasswordField rtpwM;
    private javax.swing.JPasswordField rtpwSK;
    private javax.swing.JTextField unA;
    private javax.swing.JTextField unM;
    private javax.swing.JTextField unSK;
    private javax.swing.JTextField userID1;
    private javax.swing.JTextField userID2;
    private javax.swing.JTextField userID3;
    // End of variables declaration//GEN-END:variables
}
